# Generated by Django 4.0.5 on 2022-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='students_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Кол-во студентов'),
        ),
    ]
